version: '3.6'

services:
  mongodb-server:
    image: mongo
    container_name: mongodb-server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=demo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

  api-server:
    image: nest-api-server
    container_name: api-server
    ports:
      - 8080:3000
    networks:
      - mongo_net
    
volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge
